name: Checkout the code

on: 
    workflow_dispatch:

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repo
              uses: actions/checkout@v7

            - name: List the files
              run: ls -lart


